apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k16s
spec:
  selector:
    matchLabels:
      app: nestjs-k16s
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-k16s
    spec:
      containers:
        - name: nestjs-k16s
          image: {dockerHub_username}/nestjs-k16s
          ports:
            - containerPort: 8001
